services:
  app:
    build: .
    container_name: tree-system-app
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 4000
    networks:
      - default
      - database

networks:
  database:
    external: true
    name: tree-system_default
