ALTER TABLE users
ADD COLUMN IF NOT EXISTS phone VARCHAR(30),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS district VARCHAR(120),
ADD COLUMN IF NOT EXISTS province VARCHAR(120),
ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20);
